```{r}
#Create a function that takes in a name as a string argument and returns a string of the form - "Hello name"

hello <- function(name){
  print(paste("Hello", name))
}

hello("Sam")
```
```{r}
#Create a function that will return the product of two integers

multiply <- function(a, b){
  print(a*b)
}

multiply(3,4)
```
```{r}
#create a function that accepts two arguments, an integer and a vector of integers. It returns TRUE if the integer is present in the vector, otherwise it returns FALSE. Make sure you pay careful attention to your placement of the return(FALSE) line in your function!

num_check <- function(n, v){
  if(n %in% v){
    return(TRUE)
  }else{
    return(FALSE)
  }
}

num_check(2,c(1,2,3))
```
```{r}
num_check(2,c(1,4,5))
```
```{r}
#Create a function that accepts two arguments, an integer and a vector of integers. It returns the count of the number of occurences of the integer in the input vector.

num_count <- function(n, v){
  count = 0
  for(i in 1:length(v)){
    if(n == v[i]){
      count = count + 1
    }else{
      count = count
    }
  }
  print(count)
}

num_count(2,c(1,1,2,2,3,3))
```
```{r}
num_count(1,c(1,1,2,2,3,1,4,5,5,2,2,1,3))
```
```{r}
#Create a function that accepts 3 integer values and returns their sum. However, if an integer value is evenly divisible by 3, then it does not count towards the sum. Return zero if all numbers are evenly divisible by 3

summer <- function(a, b, c){
  sum = 0
  if(!(a %% 3 == 0)){
    sum = a
  }else{
    sum = sum
  }
  
  if(!(b %% 3 == 0)){
    sum = sum + b
  }else{
    sum = sum
  }
  
  if(!(c %% 3 == 0)){
    sum = sum + c
  }else{
    sum = sum
  }
print(sum)
}

summer(7,2,3)
```
```{r}
summer(3,6,9)
```
```{r}
summer(9,11,12)
```
```{r}
#Create a function that will return TRUE if an input integer is prime. Otherwise, return FALSE

prime_check <- function(num){
  # Could put more checks for negative numbers etc...
  if (num == 2) {
    return(TRUE)
  }
  for (x in 2:(num-1)){
      
    if ((num%%x) == 0){
      return(FALSE)
    }
  }
  return(TRUE)
}
```

```{r}
prime_check(2)
prime_check(5)
prime_check(237)
```

